### ISSUE TITLE
Quotes

### ISSUE THREAD

**Issue by Drakeb0509** [LetsMakeGames/jess-windows-test-app#1]
There is a bug with the app that adds extra quotes.

Please fix, thank you.

**Comment by Drakeb0509** [comment]
There is a bug that adds extra quotes, fix it.

**Comment by Drakeb0509** [comment]
Image support would be appreciated Add it.

**Comment by wbarnes1989** [comment]
Thank you for the report Drake, I'll look into this now!

**Comment by wbarnes1989** [comment]
Hey Drake! Your issue with the additional quotes appearing when sending messages with the test app has been resolved and close. Please let us know if you run into any other issues!
